version: '3'
services:
  aspnetangular:
    image: aspnetangular:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - REMOTE_DEBUGGING
    volumes:
      - ./:/app
